### ISSUE TITLE
Something wrong in this line of code. It should be modified to “joy_.twist.axis_val_linear *= joy_.twist.scale_linear;”, then you can adjust the line speed of komodo by joy.

### ISSUE THREAD

**Issue by helon1995** [robotican/komodo2#2]
https://github.com/robotican/komodo_2.0/blob/dd25b6b83302f30ab365692c0f58c317d93426ec/komodo2_teleop/src/armadillo_teleop.cpp#L238

**Comment by roboticanyair** [comment]
The Joystick is not officially supported in the Komodo robot.
